import { normalize, songId } from './util.js';
import { TALENT_GROUP, TALENT_LIST } from './talents.js';
import { classifyVideo } from './youtube.js';

function singerFromText(text){const n=normalize(text);return TALENT_LIST.filter(t=>[t.kanji,t.eng,...t.aliases].map(normalize).filter(x=>x.length>=2).some(x=>n.includes(x))).map(t=>t.kanji);}
function titleCore(t){return normalize(t).replace(/cover|covered by|歌ってみた|original song|オリジナル曲|official mv|official music video|music video|lyric video|provided to youtube|auto generated by youtube/g,' ').replace(/\s+/g,' ').trim();}
function score(w,v){let s=0;const a=normalize(w.song),b=titleCore(v.title);if(a&&b&&(a===b||b.includes(a)||a.includes(b)))s+=100;for(const x of w.singers)if(singerFromText(v.title+' '+v.description).includes(x))s+=20;if(w.videoId===v.videoId)s+=1000;return s;}
export function buildDatabase(wikiRows, videos, rules){
  const byId=new Map(videos.map(v=>[v.videoId,v])); const videoLinks=[]; const songs=[];
  for(const w of wikiRows){
    let candidates=[];
    if(w.videoId&&byId.has(w.videoId)) candidates=[byId.get(w.videoId)];
    else candidates=videos.map(v=>({v,s:score(w,v)})).filter(x=>x.s>=100).sort((a,b)=>b.s-a.s).slice(0,10).map(x=>x.v);
    const representative=candidates.sort((a,b)=>(b.viewCount||0)-(a.viewCount||0))[0]||null;
    const singers=w.singers.length?w.singers:(representative?singerFromText(representative.title+' '+representative.description):[]);
    const sid=songId(w.song,singers,w.type);
    songs.push({songId:sid,song:w.song,singers:singers.join('、'),groups:[...new Set(singers.map(x=>TALENT_GROUP[x]||''))].filter(Boolean).join('、'),unitType:singers.length>1?'ユニット':'ソロ',songType:w.type,firstDate:w.date||representative?.publishedAt?.slice(0,10)||'',representativeVideoId:representative?.videoId||w.videoId||'',representativeUrl:representative?.url||w.videoUrl||'',viewCount:representative?.viewCount??'',channel:representative?.channelTitle||'',wikiSource:w.sourceUrl,matchStatus:representative?(w.videoId===representative.videoId?'動画ID一致':'タイトル照合'):'YouTube未照合',updatedAt:new Date().toISOString()});
    for(const v of candidates) videoLinks.push({...v,songId:sid,classification:classifyVideo(v,rules).include?'楽曲':'除外候補'});
  }
  const songMap=new Map(); for(const s of songs){const k=`${normalize(s.song)}|${s.singers}|${s.songType}`;if(!songMap.has(k))songMap.set(k,s);else{const old=songMap.get(k);if(Number(s.viewCount)>Number(old.viewCount))songMap.set(k,s);}}
  const uniqueSongs=[...songMap.values()].sort((a,b)=>a.firstDate.localeCompare(b.firstDate)||a.song.localeCompare(b.song,'ja'));
  const talentRows=[]; for(const s of uniqueSongs)for(const singer of s.singers.split('、').filter(Boolean))talentRows.push({talent:singer,song:s.song,group:TALENT_GROUP[singer]||'',unitType:s.unitType,songType:s.songType,uploadDate:s.firstDate,viewCount:s.viewCount});
  return {songs:uniqueSongs,talentRows,videos:videoLinks};
}
