import { normalize, songId, unique } from './util.js';
import { TALENT_GROUP, TALENT_LIST } from './talents.js';
import { classifyVideo } from './youtube.js';

const TALENT_MATCHERS = TALENT_LIST.map(talent => ({
  name: talent.kanji,
  aliases: unique([talent.kanji, talent.eng, ...talent.aliases])
    .map(normalize)
    .filter(alias => alias.length >= 2),
}));

function singersFromText(text) {
  const normalized = normalize(text);
  return TALENT_MATCHERS
    .filter(talent => talent.aliases.some(alias => normalized.includes(alias)))
    .map(talent => talent.name);
}

function titleCore(title) {
  return normalize(title)
    .replace(/cover|covered by|歌ってみた|original song|オリジナル曲|official mv|official music video|music video|lyric video|provided to youtube|auto generated by youtube|official audio/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function matchScore(wiki, video) {
  if (wiki.videoId && wiki.videoId === video.videoId) return 10000;
  let score = 0;
  const song = normalize(wiki.song);
  const title = titleCore(video.title);
  if (song && title) {
    if (song === title) score += 500;
    else if (title.includes(song) || song.includes(title)) score += 250;
  }

  const detected = singersFromText(`${video.title} ${video.description}`);
  for (const singer of wiki.singers) {
    if (detected.includes(singer)) score += 40;
  }

  if (wiki.date && video.publishedAt?.startsWith(wiki.date)) score += 20;
  return score;
}

function videoKind(video) {
  const text = normalize(`${video.title} ${video.description}`);
  if (/provided to youtube|auto generated by youtube/.test(text)) return 'Topic/配信音源';
  if (/lyric video/.test(text)) return 'Lyric Video';
  if (/official audio/.test(text)) return 'Official Audio';
  if (/official mv|music video/.test(text)) return 'Music Video';
  if (/歌ってみた|cover|covered by/.test(text)) return 'Cover Video';
  return 'YouTube動画';
}

export function buildDatabase(wikiRows, videos, rules) {
  const videoById = new Map(videos.map(video => [video.videoId, video]));
  const songs = [];
  const videoLinks = [];

  for (const wiki of wikiRows) {
    const ranked = [];
    for (const video of videos) {
      const score = matchScore(wiki, video);
      if (score >= 200) ranked.push({ video, score });
    }
    ranked.sort((a, b) => b.score - a.score || (b.video.viewCount || 0) - (a.video.viewCount || 0));

    let candidates = ranked.slice(0, 20).map(item => item.video);
    if (wiki.videoId && videoById.has(wiki.videoId)) {
      candidates = unique([videoById.get(wiki.videoId), ...candidates]);
    }

    const representative = [...candidates].sort((a, b) => (b.viewCount || 0) - (a.viewCount || 0))[0] || null;
    const singers = wiki.singers.length
      ? wiki.singers
      : representative
        ? singersFromText(`${representative.title} ${representative.description}`)
        : [];
    const id = songId(wiki.song, singers, wiki.type);

    songs.push({
      songId: id,
      song: wiki.song,
      singers: singers.join('、'),
      groups: unique(singers.map(singer => TALENT_GROUP[singer] || '')).join('、'),
      unitType: singers.length > 1 ? 'ユニット' : 'ソロ',
      songType: wiki.type,
      firstDate: wiki.date || representative?.publishedAt?.slice(0, 10) || '',
      representativeVideoId: representative?.videoId || wiki.videoId || '',
      representativeUrl: representative?.url || wiki.videoUrl || '',
      viewCount: representative?.viewCount ?? '',
      channel: representative?.channelTitle || '',
      wikiSource: wiki.sourceUrl,
      matchStatus: representative
        ? wiki.videoId === representative.videoId ? 'Wiki動画ID一致' : '曲名・歌唱者照合'
        : wiki.videoId ? 'YouTube動画取得不可' : 'YouTube未照合',
      updatedAt: new Date().toISOString(),
    });

    for (const video of candidates) {
      const classification = classifyVideo(video, rules);
      videoLinks.push({
        ...video,
        songId: id,
        classification: `${videoKind(video)}${classification.reasons.length ? ` / 注意:${classification.reasons.join(',')}` : ''}`,
      });
    }
  }

  const songMap = new Map();
  for (const song of songs) {
    const key = `${normalize(song.song)}|${song.singers}|${song.songType}`;
    const existing = songMap.get(key);
    if (!existing || Number(song.viewCount || 0) > Number(existing.viewCount || 0)) songMap.set(key, song);
  }

  const uniqueSongs = [...songMap.values()].sort((a, b) =>
    String(a.firstDate).localeCompare(String(b.firstDate)) || a.song.localeCompare(b.song, 'ja'));

  const talentRows = [];
  for (const song of uniqueSongs) {
    for (const singer of song.singers.split('、').filter(Boolean)) {
      talentRows.push({
        talent: singer,
        song: song.song,
        group: TALENT_GROUP[singer] || '',
        unitType: song.unitType,
        songType: song.songType,
        uploadDate: song.firstDate,
        viewCount: song.viewCount,
      });
    }
  }

  const uniqueVideoLinks = [...new Map(videoLinks.map(video => [`${video.songId}|${video.videoId}`, video])).values()];
  return { songs: uniqueSongs, talentRows, videos: uniqueVideoLinks };
}
