import fs from 'node:fs/promises';
import { stringify } from 'csv-stringify/sync';
import settings from '../config/settings.json' with { type: 'json' };
import { fetchWiki } from './wiki.js';
import { videoDetails, channelByHandle, uploads, classifyVideo } from './youtube.js';
import { buildDatabase } from './database.js';
import { pushToSheets } from './sheets.js';

const API_KEY=process.env.YOUTUBE_API_KEY;
if(!API_KEY) throw new Error('GitHub Secret YOUTUBE_API_KEY が未設定です。');
await fs.mkdir('output',{recursive:true});
const logs=[]; const log=m=>{const row={at:new Date().toISOString(),message:m};logs.push(row);console.log(m);};
const wikiRows=await fetchWiki(settings,log);
const directIds=[...new Set(wikiRows.map(x=>x.videoId).filter(Boolean))];
let details=await videoDetails(directIds,API_KEY);
const extraIds=[];
for(const c of settings.officialChannels){for(const h of c.handles){try{const ch=await channelByHandle(h,API_KEY);if(ch){log(`公式チャンネル取得: ${ch.title}`);extraIds.push(...await uploads(ch.uploads,API_KEY));break;}}catch(e){log(`チャンネル解決失敗 @${h}: ${e.message}`);}}}
const allIds=[...new Set([...directIds,...extraIds])]; details=await videoDetails(allIds,API_KEY);
const videos=[...details.values()].filter(v=>classifyVideo(v,settings.videoRules).include||directIds.includes(v.videoId));
const db=buildDatabase(wikiRows,videos,settings.videoRules);
const headers={songs:['楽曲ID','楽曲名','歌唱者','所属グループ','ソロ/ユニット','オリジナル/カバー','初出日','代表動画ID','代表URL','代表動画再生数','YouTubeチャンネル','Wikiソース','照合状態','最終更新日時'],talentRows:['タレント名','楽曲名','所属グループ','ソロorユニット','オリジナルorカバー','アップロード日','YouTube再生数'],videos:['楽曲ID','動画ID','タイトル','概要欄','公開日時','再生数','動画時間秒','チャンネル','URL','分類']};
const songRows=db.songs.map(s=>Object.values(s));
const talentRows=db.talentRows.map(s=>Object.values(s));
const videoRows=db.videos.map(v=>[v.songId,v.videoId,v.title,v.description,v.publishedAt,v.viewCount,v.durationSeconds,v.channelTitle,v.url,v.classification]);
await fs.writeFile('output/songs.csv',stringify([headers.songs,...songRows]));
await fs.writeFile('output/talent_rows.csv',stringify([headers.talentRows,...talentRows]));
await fs.writeFile('output/videos.csv',stringify([headers.videos,...videoRows]));
await fs.writeFile('output/wiki_raw.json',JSON.stringify(wikiRows,null,2));
await fs.writeFile('output/logs.json',JSON.stringify(logs,null,2));
await pushToSheets(process.env.SHEETS_WEB_APP_URL,process.env.SHEETS_WEB_APP_TOKEN,{spreadsheetId:settings.spreadsheetId,sheets:settings.sheets,data:{songs:{headers:headers.songs,rows:songRows},talentRows:{headers:headers.talentRows,rows:talentRows},videos:{headers:headers.videos,rows:videoRows},logs:{headers:['日時','メッセージ'],rows:logs.map(x=>[x.at,x.message])}}});
log(`完了: 楽曲 ${songRows.length} / タレント別 ${talentRows.length} / 動画 ${videoRows.length}`);
