export const TALENT_LIST = [
  { kanji: 'ときのそら',                  eng: 'tokino-sora',              aliases: ['そら', 'sora', 'tokinosora', 'tokino sora'] },
  { kanji: 'ロボ子さん',                  eng: 'roboco-san',               aliases: ['ロボ子', 'roboco', 'robocosan'] },
  { kanji: 'AZKi',                       eng: 'azki',                     aliases: ['Azki', 'AZKI'] },
  { kanji: 'さくらみこ',                  eng: 'sakura-miko',              aliases: ['みこ', 'miko', 'sakuramiko', 'sakura miko'] },
  { kanji: '星街すいせい',                eng: 'hoshimachi-suisei',        aliases: ['すいせい', 'suisei', 'hoshimachi suisei'] },
  { kanji: 'アキ・ローゼンタール',        eng: 'aki-rosenthal',            aliases: ['アキ', 'aki', 'aki rosenthal'] },
  { kanji: '赤井はあと',                  eng: 'akai-haato',               aliases: ['はあと', 'haato', 'haachama', 'ハアチャマ', 'akai haato'] },
  { kanji: '白上フブキ',                  eng: 'shirakami-fubuki',         aliases: ['フブキ', 'fubuki', 'shirakami fubuki'] },
  { kanji: '夏色まつり',                  eng: 'natsuiro-matsuri',         aliases: ['まつり', 'matsuri', 'natsuiro matsuri'] },
  { kanji: '紫咲シオン',                  eng: 'murasaki-shion',           aliases: ['シオン', 'shion', 'murasaki shion'] },
  { kanji: '百鬼あやめ',                  eng: 'nakiri-ayame',             aliases: ['あやめ', 'ayame', 'nakiri ayame'] },
  { kanji: '癒月ちょこ',                  eng: 'yuzuki-choco',             aliases: ['ちょこ', 'choco', 'yuzuki choco'] },
  { kanji: '大空スバル',                  eng: 'oozora-subaru',            aliases: ['スバル', 'subaru', 'oozora subaru'] },
  { kanji: '大神ミオ',                    eng: 'ookami-mio',               aliases: ['ミオ', 'mio', 'ookami mio'] },
  { kanji: '猫又おかゆ',                  eng: 'nekomata-okayu',           aliases: ['おかゆ', 'okayu', 'nekomata okayu'] },
  { kanji: '戌神ころね',                  eng: 'inugami-korone',           aliases: ['ころね', 'korone', 'inugami korone'] },
  { kanji: '兎田ぺこら',                  eng: 'usada-pekora',             aliases: ['ぺこら', 'pekora', 'usada pekora'] },
  { kanji: '不知火フレア',                eng: 'shiranui-flare',           aliases: ['フレア', 'flare', 'shiranui flare'] },
  { kanji: '白銀ノエル',                  eng: 'shirogane-noel',           aliases: ['ノエル', 'noel', 'shirogane noel'] },
  { kanji: '宝鐘マリン',                  eng: 'houshou-marine',           aliases: ['マリン', 'marine', 'houshou marine'] },
  { kanji: '天音かなた',                  eng: 'amane-kanata',             aliases: ['かなた', 'kanata', 'amane kanata'] },
  { kanji: '角巻わため',                  eng: 'tsunomaki-watame',         aliases: ['わため', 'watame', 'tsunomaki watame'] },
  { kanji: '常闇トワ',                    eng: 'tokoyami-towa',            aliases: ['トワ', 'towa', 'tokoyami towa'] },
  { kanji: '姫森ルーナ',                  eng: 'himemori-luna',            aliases: ['ルーナ', 'luna', 'himemori luna'] },
  { kanji: '雪花ラミィ',                  eng: 'yukihana-lamy',            aliases: ['ラミィ', 'lamy', 'yukihana lamy'] },
  { kanji: '桃鈴ねね',                    eng: 'momosuzu-nene',            aliases: ['ねね', 'nene', 'momosuzu nene'] },
  { kanji: '獅白ぼたん',                  eng: 'shishiro-botan',           aliases: ['ぼたん', 'botan', 'shishiro botan'] },
  { kanji: '尾丸ポルカ',                  eng: 'omaru-polka',              aliases: ['ポルカ', 'polka', 'omaru polka'] },
  { kanji: 'ラプラス・ダークネス',        eng: 'la-darknesss',             aliases: ['ラプラス', 'laplus', 'la+', 'la darknesss', 'la+ darknesss'] },
  { kanji: '鷹嶺ルイ',                    eng: 'takane-lui',               aliases: ['ルイ', 'lui', 'takane lui'] },
  { kanji: '博衣こより',                  eng: 'hakui-koyori',             aliases: ['こより', 'koyori', 'hakui koyori'] },
  { kanji: '沙花叉クロヱ',                eng: 'sakamata-chloe',           aliases: ['クロヱ', 'chloe', 'sakamata chloe'] },
  { kanji: '風真いろは',                  eng: 'kazama-iroha',             aliases: ['いろは', 'iroha', 'kazama iroha'] },
  { kanji: 'アユンダ・リス',              eng: 'ayunda-risu',              aliases: ['リス', 'risu', 'ayunda risu'] },
  { kanji: 'ムーナ・ホシノヴァ',          eng: 'moona-hoshinova',          aliases: ['ムーナ', 'moona', 'moona hoshinova'] },
  { kanji: 'アイラニ・イオフィフティーン',eng: 'airani-iofifteen',         aliases: ['イオフィ', 'iofi', 'iofifteen', 'airani iofifteen'] },
  { kanji: 'クレイジー・オリー',          eng: 'kureiji-ollie',            aliases: ['オリー', 'ollie', 'kureiji ollie'] },
  { kanji: 'アーニャ・メルフィッサ',      eng: 'anya-melfissa',            aliases: ['アーニャ', 'anya', 'melfissa', 'anya melfissa'] },
  { kanji: 'パヴォリア・レイネ',          eng: 'pavolia-reine',            aliases: ['レイネ', 'reine', 'pavolia reine'] },
  { kanji: 'ベスティア・ゼータ',          eng: 'vestia-zeta',              aliases: ['ゼータ', 'zeta', 'vestia zeta'] },
  { kanji: 'カエラ・コヴァルスキア',      eng: 'kaela-kovalskia',          aliases: ['カエラ', 'kaela', 'kovalskia', 'kaela kovalskia'] },
  { kanji: 'こぼ・かなえる',              eng: 'kobo-kanaeru',             aliases: ['こぼ', 'kobo', 'kanaeru', 'kobo kanaeru'] },
  { kanji: '森カリオペ',                  eng: 'mori-calliope',            aliases: ['カリオペ', 'calliope', 'calli', 'mori calliope'] },
  { kanji: '小鳥遊キアラ',                eng: 'takanashi-kiara',          aliases: ['キアラ', 'kiara', 'takanashi kiara'] },
  { kanji: '一伊那尓栖',                  eng: 'ninomae-inanis',           aliases: ['イナ', 'ina', 'inanis', "ina'nis", 'ninomae inanis'] },
  { kanji: 'がうる・ぐら',                eng: 'gawr-gura',                aliases: ['ぐら', 'gura', 'gawr gura'] },
  { kanji: 'ワトソン・アメリア',          eng: 'watson-amelia',            aliases: ['アメリア', 'amelia', 'ame', 'watson amelia'] },
  { kanji: 'IRyS',                       eng: 'irys',                     aliases: ['IRYS', 'アイリス'] },
  { kanji: 'セレス・ファウナ',            eng: 'ceres-fauna',              aliases: ['ファウナ', 'fauna', 'ceres fauna'] },
  { kanji: 'オーロ・クロニー',            eng: 'ouro-kronii',              aliases: ['クロニー', 'kronii', 'ouro kronii'] },
  { kanji: '七詩ムメイ',                  eng: 'nanashi-mumei',            aliases: ['ムメイ', 'mumei', 'nanashi mumei'] },
  { kanji: 'ハコス・ベールズ',            eng: 'hakos-baelz',              aliases: ['ベールズ', 'baelz', 'bae', 'hakos baelz'] },
  { kanji: 'シオリ・ノヴェラ',            eng: 'shiori-novella',           aliases: ['シオリ', 'novella', 'shiori novella'] },
  { kanji: '古石ビジュー',                eng: 'koseki-bijou',             aliases: ['ビジュー', 'bijou', 'biju', 'koseki bijou'] },
  { kanji: 'ネリッサ・レイヴンクロフト',  eng: 'nerissa-ravencroft',       aliases: ['ネリッサ', 'nerissa', 'ravencroft', 'nerissa ravencroft'] },
  { kanji: 'フワワ・アビスガード',        eng: 'fuwawa-abyssgard',         aliases: ['フワワ', 'fuwawa', 'fuwamoco', 'abyssgard'] },
  { kanji: 'モココ・アビスガード',        eng: 'mococo-abyssgard',         aliases: ['モココ', 'mococo', 'fuwamoco'] },
  { kanji: '火威青',                      eng: 'hiodoshi-ao',              aliases: ['青', 'hiodoshi ao'] },
  { kanji: '音乃瀬奏',                    eng: 'otonose-kanade',           aliases: ['奏', 'kanade', 'otonose kanade'] },
  { kanji: '一条莉々華',                  eng: 'ichijou-ririka',           aliases: ['莉々華', 'ririka', 'ichijou ririka'] },
  { kanji: '儒烏風亭らでん',              eng: 'juufuutei-raden',          aliases: ['らでん', 'raden', 'juufuutei raden'] },
  { kanji: '轟はじめ',                    eng: 'todoroki-hajime',          aliases: ['はじめ', 'hajime', 'todoroki hajime'] },
  { kanji: 'エリザベス・ローズ・ブラッドフレイム', eng: 'elizabeth-rose-bloodflam', aliases: ['エリザベス', 'elizabeth', 'elizabeth rose', 'bloodflame', 'bloodflam'] },
  { kanji: 'ジジ・ムリン',                eng: 'gigi-murin',               aliases: ['ジジ', 'gigi', 'murin', 'gigi murin'] },
  { kanji: 'セシリア・イマーグリーン',    eng: 'cecilia-immergreen',       aliases: ['セシリア', 'cecilia', 'immergreen', 'cecilia immergreen'] },
  { kanji: 'ラオーラ・パンテーラ',        eng: 'raora-panthera',           aliases: ['ラオーラ', 'raora', 'panthera', 'raora panthera'] },
  { kanji: '響咲リオナ',                  eng: 'isaki-riona',              aliases: ['リオナ', 'riona', 'isaki riona'] },
  { kanji: '虎金妃笑虎',                  eng: 'koganei-niko',             aliases: ['ニコ', 'niko', 'koganei niko'] },
  { kanji: '水宮枢',                      eng: 'mizumiya-su',              aliases: ['枢', 'mizumiya su'] },
  { kanji: '輪堂千速',                    eng: 'rindo-chihaya',            aliases: ['千速', 'chihaya', 'rindo chihaya'] },
  { kanji: '綺々羅々ヴィヴィ',            eng: 'kikirara-vivi',            aliases: ['ヴィヴィ', 'vivi', 'kikirara vivi'] },
];

export const TALENT_GROUP = Object.freeze({
  'ときのそら': 'gen0',
  'ロボ子さん': 'gen0',
  'AZKi': 'gen0',
  'さくらみこ': 'gen0',
  '星街すいせい': 'gen0',
  'アキ・ローゼンタール': 'gen1',
  '赤井はあと': 'gen1',
  '白上フブキ': 'gen1/GAMERS',
  '夏色まつり': 'gen1',
  '紫咲シオン': 'gen2',
  '百鬼あやめ': 'gen2',
  '癒月ちょこ': 'gen2',
  '大空スバル': 'gen2',
  '大神ミオ': 'GAMERS',
  '猫又おかゆ': 'GAMERS',
  '戌神ころね': 'GAMERS',
  '兎田ぺこら': 'gen3',
  '不知火フレア': 'gen3',
  '白銀ノエル': 'gen3',
  '宝鐘マリン': 'gen3',
  '天音かなた': 'gen4',
  '角巻わため': 'gen4',
  '常闇トワ': 'gen4',
  '姫森ルーナ': 'gen4',
  '雪花ラミィ': 'gen5',
  '桃鈴ねね': 'gen5',
  '獅白ぼたん': 'gen5',
  '尾丸ポルカ': 'gen5',
  'ラプラス・ダークネス': 'holoX',
  '鷹嶺ルイ': 'holoX',
  '博衣こより': 'holoX',
  '沙花叉クロヱ': 'holoX',
  '風真いろは': 'holoX',
  'アユンダ・リス': 'ID1',
  'ムーナ・ホシノヴァ': 'ID1',
  'アイラニ・イオフィフティーン': 'ID1',
  'クレイジー・オリー': 'ID2',
  'アーニャ・メルフィッサ': 'ID2',
  'パヴォリア・レイネ': 'ID2',
  'ベスティア・ゼータ': 'ID3',
  'カエラ・コヴァルスキア': 'ID3',
  'こぼ・かなえる': 'ID3',
  '森カリオペ': 'Myth',
  '小鳥遊キアラ': 'Myth',
  '一伊那尓栖': 'Myth',
  'がうる・ぐら': 'Myth',
  'ワトソン・アメリア': 'Myth',
  'IRyS': 'Promise',
  'セレス・ファウナ': 'Promise',
  'オーロ・クロニー': 'Promise',
  '七詩ムメイ': 'Promise',
  'ハコス・ベールズ': 'Promise',
  'シオリ・ノヴェラ': 'Advent',
  '古石ビジュー': 'Advent',
  'ネリッサ・レイヴンクロフト': 'Advent',
  'フワワ・アビスガード': 'Advent',
  'モココ・アビスガード': 'Advent',
  '火威青': 'ReGLOSS',
  '音乃瀬奏': 'ReGLOSS',
  '一条莉々華': 'ReGLOSS',
  '儒烏風亭らでん': 'ReGLOSS',
  '轟はじめ': 'ReGLOSS',
  'エリザベス・ローズ・ブラッドフレイム': 'Justice',
  'ジジ・ムリン': 'Justice',
  'セシリア・イマーグリーン': 'Justice',
  'ラオーラ・パンテーラ': 'Justice',
  '響咲リオナ': 'FLOW GLOW',
  '虎金妃笑虎': 'FLOW GLOW',
  '水宮枢': 'FLOW GLOW',
  '輪堂千速': 'FLOW GLOW',
  '綺々羅々ヴィヴィ': 'FLOW GLOW',
});

export const OFFICIAL_SLUG_OVERRIDES = Object.freeze({
  'さくらみこ': 'sakuramiko',
  'エリザベス・ローズ・ブラッドフレイム': 'elizabeth-rose-bloodflame',
});
